### ISSUE TITLE
It works at first attempt, but then cannot run anymore

### ISSUE THREAD

**Issue by uliarizki** [abdulsalam01/tokopedia-scrapper#1]
So I have executed the script and scrapped 32 lines of data in csv successfully then it got an error so scraping stopped. But when I re run the script this showed up:
```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Program Files\Python310\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Program Files\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chromedriver.storage.googleapis.com', port=443): Max retries exceeded with url: /LATEST_RELEASE_97.0.4692 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
```

is it because of my IP getting blocked or something else? I am new to scraping and hope you can help me fix this problem.
Thank you.

**Comment by abdulsalam01** [comment]
It's blocking by IP, try to use proxy on your computer and then run it again.

uncomment this line of code in **config/WebClientConfig.java**:
`
//        WebClient webClient = new WebClient(browser, (String)proxy[0], (int)proxy[1]);
`
`
        // set proxy
`
`
//        DefaultCredentialsProvider credentialsProvider = (DefaultCredentialsProvider) webClient.getCredentialsProvider();
`
`
//        credentialsProvider.addCredentials("scrapper_proxy", "scrapperProxy135");
`

and try to run it again
